export const SET_ACTIVE_QUIZ = "SET_ACTIVE_QUIZ";
export const EDIT_QUESTION_OF_ACTIVE_QUIZ = "EDIT_QUESTION_OF_ACTIVE_QUIZ";
export const ADD_QUESTION_TO_ACTIVE_QUIZ = "ADD_QUESTION_TO_ACTIVE_QUIZ";
export const DELETE_QUESTION_FROM_ACTIVE_QUIZ =
  "DELETE_QUESTION_FROM_ACTIVE_QUIZ";
