export const SET_QUIZ_TITLE = "SET_QUIZ_TITLE";
export const SET_QUIZ_DEADLINE = "SET_QUIZ_DEADLINE";
export const SET_QUIZ_TOTAL_DURATION = "SET_QUIZ_TOTAL_DURATION";
export const SET_QUIZ_PER_QUESTION_DURATION = "SET_QUIZ_PER_QUESTION_DURATION";
export const SET_QUIZ_TYPE = "SET_QUIZ_TYPE";
export const ADD_QUIZ_CLASSES = "ADD_QUIZ_CLASSES";
export const REMOVE_QUIZ_CLASSES = "REMOVE_QUIZ_CLASSES";
